# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finduser.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='finduser.proto',
  package='messaging',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x66induser.proto\x12\tmessaging\"\xac\x02\n\x08\x46indUser\x12\x13\n\x0bpacket_type\x18\x01 \x02(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x15\n\rlist_of_users\x18\x05 \x01(\t\x12\x0e\n\x06sender\x18\x10 \x01(\t\x12\x0f\n\x07message\x18\x11 \x01(\t\x12\n\n\x02id\x18\x12 \x01(\x05\x12\x10\n\x08sequence\x18\x13 \x01(\x05\x12\r\n\x05\x63ount\x18\x14 \x01(\x05\x12\x16\n\x0e\x65ncrypted_text\x18\x0b \x01(\x0c\x12\n\n\x02iv\x18\x0c \x01(\x0c\x12\x0b\n\x03tag\x18\r \x01(\x0c\x12\x10\n\x08receiver\x18\x04 \x01(\t\x12\r\n\x05nonce\x18\x06 \x01(\x05\x12\x13\n\x0breceiver_iv\x18\x08 \x01(\x0c\x12\x14\n\x0creceiver_tag\x18\t \x01(\x0c\x12\x17\n\x0fticket_receiver\x18\n \x01(\x0c')
)




_FINDUSER = _descriptor.Descriptor(
  name='FindUser',
  full_name='messaging.FindUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet_type', full_name='messaging.FindUser.packet_type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='messaging.FindUser.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list_of_users', full_name='messaging.FindUser.list_of_users', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='messaging.FindUser.sender', index=3,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='messaging.FindUser.message', index=4,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='messaging.FindUser.id', index=5,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='messaging.FindUser.sequence', index=6,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='messaging.FindUser.count', index=7,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encrypted_text', full_name='messaging.FindUser.encrypted_text', index=8,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iv', full_name='messaging.FindUser.iv', index=9,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='messaging.FindUser.tag', index=10,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='messaging.FindUser.receiver', index=11,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='messaging.FindUser.nonce', index=12,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_iv', full_name='messaging.FindUser.receiver_iv', index=13,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_tag', full_name='messaging.FindUser.receiver_tag', index=14,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ticket_receiver', full_name='messaging.FindUser.ticket_receiver', index=15,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=330,
)

DESCRIPTOR.message_types_by_name['FindUser'] = _FINDUSER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FindUser = _reflection.GeneratedProtocolMessageType('FindUser', (_message.Message,), dict(
  DESCRIPTOR = _FINDUSER,
  __module__ = 'finduser_pb2'
  # @@protoc_insertion_point(class_scope:messaging.FindUser)
  ))
_sym_db.RegisterMessage(FindUser)


# @@protoc_insertion_point(module_scope)
