# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finduser.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='finduser.proto',
  package='messaging',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x66induser.proto\x12\tmessaging\"[\n\x08\x46indUser\x12\x13\n\x0bpacket_type\x18\x01 \x02(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\tipaddress\x18\x03 \x01(\x0c\x12\x15\n\rlist_of_users\x18\x04 \x01(\t')
)




_FINDUSER = _descriptor.Descriptor(
  name='FindUser',
  full_name='messaging.FindUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet_type', full_name='messaging.FindUser.packet_type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='messaging.FindUser.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipaddress', full_name='messaging.FindUser.ipaddress', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list_of_users', full_name='messaging.FindUser.list_of_users', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['FindUser'] = _FINDUSER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FindUser = _reflection.GeneratedProtocolMessageType('FindUser', (_message.Message,), dict(
  DESCRIPTOR = _FINDUSER,
  __module__ = 'finduser_pb2'
  # @@protoc_insertion_point(class_scope:messaging.FindUser)
  ))
_sym_db.RegisterMessage(FindUser)


# @@protoc_insertion_point(module_scope)
